Transform: AWS::Serverless-2016-10-31

Parameters:
  CodeBucket:
    Type: String
  CodeKey:
    Type: String

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
  LFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 
        Bucket: !Ref CodeBucket
        Key: !Ref CodeKey
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
      Runtime: python3.8
      Handler: handler.handler
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Count
        Type: String
      TableName: NumberOfVisitors
      Tags:
        Count: 0
