Transform: AWS::Serverless-2016-10-31

Parameters:
  CodeU:
    Type: String

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
  LFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://oliver-cloud-resume-backend/python.zip
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
      Runtime: python3.8
      Handler: handler.handler
